// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SI_HZs_lEyfd84CgN58LOPl0dBkJhuU',
    appId: '1:272944052495:web:a290500a62648db30ca67a',
    messagingSenderId: '272944052495',
    projectId: 'si-itik-7b3e6',
    authDomain: 'si-itik-7b3e6.firebaseapp.com',
    databaseURL: 'https://si-itik-7b3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-itik-7b3e6.firebasestorage.app',
    measurementId: 'G-JRYB9DGW81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBifKc4O7oZu086z3kK_UQyFaoyinKykSA',
    appId: '1:272944052495:android:025c209e267131500ca67a',
    messagingSenderId: '272944052495',
    projectId: 'si-itik-7b3e6',
    databaseURL: 'https://si-itik-7b3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-itik-7b3e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLyfNJTA0KJoWtCyG78bQx8KD7eH7dU-8',
    appId: '1:272944052495:ios:e44fbbb4b25808400ca67a',
    messagingSenderId: '272944052495',
    projectId: 'si-itik-7b3e6',
    databaseURL: 'https://si-itik-7b3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-itik-7b3e6.firebasestorage.app',
    iosClientId: '272944052495-q63hjlt0rou69aiu4vafq9h7v27k65s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.siItik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLyfNJTA0KJoWtCyG78bQx8KD7eH7dU-8',
    appId: '1:272944052495:ios:e44fbbb4b25808400ca67a',
    messagingSenderId: '272944052495',
    projectId: 'si-itik-7b3e6',
    databaseURL: 'https://si-itik-7b3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-itik-7b3e6.firebasestorage.app',
    iosClientId: '272944052495-q63hjlt0rou69aiu4vafq9h7v27k65s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.siItik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8SI_HZs_lEyfd84CgN58LOPl0dBkJhuU',
    appId: '1:272944052495:web:a290500a62648db30ca67a',
    messagingSenderId: '272944052495',
    projectId: 'si-itik-7b3e6',
    authDomain: 'si-itik-7b3e6.firebaseapp.com',
    databaseURL: 'https://si-itik-7b3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-itik-7b3e6.firebasestorage.app',
    measurementId: 'G-JRYB9DGW81',
  );
}